import Edge from "./Edge.js";
import Grapth from "./Grapth.js";
import Person from "./Person.js";

let trang = new Person(`Nguyen Minh Trang`, 23, `0978155603`);
let duc = new Person(`Doan Nguyen Duc`, 27, `0878155603`);
let trung = new Person(`Nguyen Duc Trung`, 25, `0778155603`);
let mi = new Person(`Tran Ha Mi`, 24, `0678155603`);
let tung = new Person(`Hoang Bach Tung`, 21, `0578155603`);
let minh = new Person(`Do Tien Minh`, 29, `0478155603`);
let khoan = new Person(`Phung Khac Khoan`, 33, `0378155603`);
let trangDuc = new Edge(trang, duc);
let trangTrung = new Edge(trang, trung);
let ducMi = new Edge(duc, mi);
let trungTung = new Edge(trung, tung);
let tungDuc = new Edge(tung, duc);
let tungKhoan = new Edge(tung, khoan);
let tungMinh = new Edge(tung, minh);
let miDuc = new Edge(mi, duc);
let miKhoan = new Edge(mi, khoan);
let grapth = new Grapth();
grapth.addVertice(trang);
grapth.addVertice(duc);
grapth.addVertice(trung);
grapth.addVertice(mi);
grapth.addVertice(tung);
grapth.addVertice(minh);
grapth.addVertice(khoan);
grapth.addEdge(trangDuc);
grapth.addEdge(trangTrung);
grapth.addEdge(ducMi);
grapth.addEdge(trungTung);
grapth.addEdge(tungDuc);
grapth.addEdge(tungKhoan);
grapth.addEdge(tungMinh);
grapth.addEdge(miDuc);
grapth.addEdge(miKhoan);

console.log(grapth.findNearestVertice(trung.phoneNumber));